package lol.gilliard;

import java.util.Arrays;
import java.util.List;

public class OwlFacts {

    public static final List<String> facts = Arrays.asList(
            "Owls are typified by an upright stance, a large, broad head, binocular vision, binaural hearing, sharp talons, and feathers adapted for silent flight.",
            "Owls hunt mostly small mammals, insects, and other birds, although a few species specialize in hunting fish.",
            "Owls are found in all regions of the Earth except polar ice caps and some remote islands.",
            "Owls have 14 neck vertebrae compared to seven in humans, which makes their necks more flexible.",
            "Owls can rotate their heads and necks as much as 270°.",
            "The feathers around an owl's eyes can be adjusted to sharply focus on sounds from varying distances",
            "Owls' eyes are fixed in their sockets so they must turn their entire heads to change views.",
            "Owls are farsighted. They cannot clearly see anything closer than a few centimetres, but their far vision, particularly in low light, is exceptionally good.",
            "The Elf Owl is the smallest type of owl. Elf Owls weigh as little as 31g.",
            "The largest owls are Eurasian Eagle Owls and Blakiston's Fish Owl. They have a wingspan over a metre and weigh 4.2kg",
            "Many types of owls have asymmetric ears, for better locating the source of a sound.",
            "Owl plumage is generally used as camouflage, although many have distinctive face and head markings as well as bright eyes.",
            "Typically male owls are slightly smaller than females.",
            "Owls are carnivorous birds of prey and live mainly on a diet of insects and small rodents such as mice, rats, and hares.",
            "Some owls are specially adapted to hunt fish",
            "Most owls have an innate ability to fly almost silently and also more slowly than other birds of prey.",
            "Most owls are nocturnal, but not all.",
            "Owls' feathers have several unique characteristics which allow them to fly almost silently",
            "Barn Owls feathers are not waterproof so they cannot hunt in the rain.",
            "Owls can struggle to keep warm, because of their lack of waterproofing",
            "Most nocturnal birds use echolocation when flying at night, but owls rely on their excellent night vision",
            "Owls use the tiny difference in time between a sound arriving at each ear. When sounds arrive at both ears simultaneously the owl is looking directly at the source.",
            "Owls use their flat faces to focus sound into their ears. They can change the shape of their face to listen to different things.",
            "Some owls have tufts on top of their heads that look like ears, but they are just feathers. Their ears are on the sides of their head.",
            "The Great Horned Owl has the strongest gripping talons of the owls",
            "Owls use their sharp beaks like scissors to cut into their prey",
            "Snowy Owls are almost completely white, with just a few black flecks so they are well camouflaged in snowy surroundings.",
            "There are over 200 species of owls",
            "Many owls are nocturnal, but some are crepuscular (active at dusk and dawn) and a few are active during the day",
            "The Burrowing Owl and the Short-Eared Owl are not nocturnal.",
            "Many owls can fly silently, but those that hunt fish do not.",
            "Owls' usually kill their prey with a sharp beak and powerful claws before swallowing it whole",
            "After swallowing their prey whole, owls regurgitate parts like fur and bones in a pellet",
            "Owls eggs are almost spherical",
            "Owls typically lay 3 or 4 eggs in a season but sometimes up to 12",
            "Owls have transparent 3rd eyelids so they can wink or blink without breaking their stare",
            "Among the Kikuyu of Kenya, it was believed that owls were harbingers of death. If one saw an owl or heard its hoot, someone was going to die.",
            "In modern Japan, owls are regarded as lucky and are carried in the form of a talisman or charm.",
            "The modern West generally associates owls with wisdom and vigilance.",
            "The Ancient Greek city of Athens had an owl as its symbol.",
            "Shakespeare considered owls to be an ill-omen.",
            "In Roman times Pliny called the owl a funereal bird, a monster of the night, the very abomination of human kind.",
            "Pliny the Elder reports that owls' eggs were used in ancient Rome as a hangover cure",
            "Hindu goddess Lakshmi is sometimes pictured riding on an owl",
            "In most Native American folklore, owls are a symbol of death.",
            "The Aztec god of death, Mictlantecuhtli, was often depicted with owls.",
            "A purpose-built owl-house (or owlery) can be used to encourage owls to roost and help control rodent populations.",
            "In 2013 in Inverness, Scotland, a man was attacked by an Eagle Owl and suffered from bleeding and shock",
            "Photographer Eric Hosking lost an eye while attempting to photograph a Tawny Owl.",
            "Owls generally have a hunting territory which is away from where they sleep during the day",
            "Most owl species hunt from a perch and swoop down with their talons forward when they see prey",
            "Owls sometimes make a tent-shape with their wings to hide prey they have caught from other predators",
            "When prey is plentiful, owls can store surplus food in a cache near their nest",
            "Like other birds owls cannot chew, so they cut their prey with their beaks and swallow pieces whole",
            "An owl's eyes can account for up to 5% of its bodyweight",  // wow
            "Owls' eyes are not spherical but tubular, which is why an owl has to move its head to look at something",
            "Owls have very good night vision but are almost colourblind as their eyes have more rods and fewer cones.",
            "As well as excellent night vision owls can see better than humans in bright light.",
            "When an owl attacks it will fly directly towards its prey so that it can adjust if it hears the prey move",
            "Owls have 5 different types of feathers over their body",
            "Many smaller owls have 'false eyes', ie dark spots on the back of the head, to confuse predators",
            "Some owls have ear tufts, but these have nothing to do with an owl's hearing.",
            "Owls' ear tufts indicate moods such as fear, anger and excitement.",
            "Owls use their beak and talons for preening.",
            "Owls molt yearly, replacing all their feathers over a three-month period.",
            "Harry Potter's owl Hedwig is a two-foot tall Snowy Owl.",
            "Hedwig, Harry Potter's owl, is described as female but only male Snowy Owls are pure white.",
            "Ron Weasley, has an owl named Pigwidgeon, a Little Owl or maybe a Scops Owl, nobody is sure.",
            "Draco Malfoy has as his familiar this Eurasian Eagle-Owl",
            "JK Rowling's owls bridge the magical and muggle world, carrying messages, packages, and even Nimbus 2000s",
            "Daniel Radcliffe wore thick leather armour under his robes in the scenes with Hedwig - Snowy Owls' claws are powerful enough to kill ducks and other prey",
            "Seven different owls played the role of Hedwig in the Harry Potter movies. Their names are Gizmo, Kasper, Oops, Swoops, Oh Oh, Elmo and Bandit.",
            "The earliest known depiction of an owl by humans is in the Chauvet Cave in France - A Long-Eared Owl drawn around 40-45 thousand years ago.",
            "Great Grey Owls are some of the largest owls, but specialize in small rodents such as mice and voles.",
            "Percy's owl in Harry Potter is a Screech Owl. As the name suggests, Screech Owls do NOT hoot like most owls.",
            "Owls have three front toes and one back toe on each foot. But one of the front claws is opposable, and rotates backward the way we use our thumb.",
            "Owls are extremely stressed by being near other owls.",
            "Owls do not like each other's company. Movie scenes with many owls are sometimes created using compositing of several individuals",
            "Large species of owls sometimes eat smaller species.",
            "The tiny Victorian cage used to keep Harry's owl in the Harry Potter movies would be illegal to keep an owl in either the U.S. or Great Britain.",
            "Owls are secretive in the daytime, because they are often attacked by crows, ravens, jays, robins, and other birds.",
            "Proceeds from https://owlstuff.com/ go to help owl conservation societies.",
            "Rarely owls can kill cats, but it is usually the other way around.",
            "David Bowie's Goblin King from the movie Labyrinth first appears on-screen as a Barn Owl.",
            "A group of owls is called a Parliament. This originated with CS Lewis's Chronicles of Narnia.",
            "The Northern Hawk Owl can detect a tiny vole up to half a mile away.",
            "A barn owl can eat up to 1,000 mice each year",
            "Most owls do no migrate, but some are nomadic",
            "Owls have been found in the fossil record up to 58 million years ago.",
            "The largest recorded owl fossil, Orinmegalonyx oteroi, stood about three feet tall.",
            "The biggest modern threats to owls are habitat loss, pesticides that poison the birds and their food supplies, and human persecution because of negative superstitions.",
            "If turning their head cuts off blood supply, a blood pooling system kicks in that provides temporary oxygen until the owl moves back to a more comfortable position.",
            "Baby owls are called 'Owlets'",
            "Owl parents always feed the oldest and strongest owlet before its siblings.",
            "Aside from hooting, owls make a variety of calls, from screeches to whistles to squeaks.",
            "Elf Owls in Southern USA and Mexico sometimes nest in cactus plants",
            "Long-legged burrowing owls sometimes move into empty burrows dug out by prarie dogs",
            "A 2004 study found that Burrowing Owls use their poop as bait to attract dung beetles - their favourite food",
            "Athena was an Ancient Greek warrior goddess and the owl was considered the protector of her armies going into war.",
            "In Japan, there are owl cafés, where you can hang out with owls while drinking tea. " // 100th Owl Fact!!

    );


}
